name: Deploy

on: [push]

jobs:
  deploy:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install dependencies
        run: npm install
        
      - name: npm build
        run:
          npm run build --if-present
          npm ci
        env:
          CI: true
        
      - name: Zip
        run: (cd dist && zip -r ../function.zip .)
        
      - name: Deploy to AWS
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: dev_githubAction
          zip_file: function.zip
